version: '3'
services:
  zoo1:
    image: zookeeper:3.8.1
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    restart: always
  
  zoo2:
    image: zookeeper:3.8.1
    container_name: zoo2
    hostname: zoo2
    ports:
      - 2182:2181
    volumes:
      - ./zoo2/data:/data
      - ./zoo2/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    restart: always
  
  zoo3:
    image: zookeeper:3.8.1
    container_name: zoo3
    hostname: zoo3
    ports:
      - 2183:2181
    volumes:
      - ./zoo3/data:/data
      - ./zoo3/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    restart: always

  zkui:
    image: qnib/zkui
    container_name: zkui
    depends_on:
     - zoo1
     - zoo2
     - zoo3
    ports:
      - 9090:9090
    environment:
      TZ: Asia/Shanghai
      ZKUI_ZK_SERVER: zoo1:2181 zoo2:2181 zoo3:2181
    restart: always