version: '3'
networks:
  bigdata:
    driver: default
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

services:
  zoo1:
    image: zookeeper:3.8.1
    container_name: zoo1
    ports:
      - 2181:2181
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      bigdata:
        ipv4_address: 172.25.0.11
    restart: always
  
  zoo2:
    image: zookeeper:3.8.1
    container_name: zoo2
    ports:
      - 2182:2181
    volumes:
      - ./zoo2/data:/data
      - ./zoo2/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      bigdata:
        ipv4_address: 172.25.0.12
    restart: always
  
  zoo3:
    image: zookeeper:3.8.1
    container_name: zoo3
    ports:
      - 2183:2181
    volumes:
      - ./zoo3/data:/data
      - ./zoo3/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      bigdata:
        ipv4_address: 172.25.0.13
    restart: always
